import type { Dictionary } from "./types";

const en: Dictionary = {
  meta: {
    title: "Ankora — Operational Intelligence",
    description:
      "Ankora combines AI orchestration with dedicated human Operations Managers to remove the operational weight of modern life.",
    homeTitle: "Ankora | Personal Operations Management for Executives & Founders",
    homeDescription: "Ankora combines a dedicated human Operations Manager with AI orchestration to take end-to-end ownership of personal, household, vendor, administrative, travel and business operations for executives, founders and busy families.",
    aboutTitle: "About Ankora | Personal Operations Management Company",
    aboutDescription: "Ankora is an Israeli Personal Operations Management company. Learn about our Human + AI model, the Operational Intelligence philosophy behind it, and who we serve.",
  },
  nav: {
    solutions: "Who it's for",
    howItWorks: "How it works",
    technology: "Technology",
    about: "About",
    pricing: "Pricing",
    roi: "ROI Calculator",
    coverage: "Areas of Coverage",
    cta: "Book a call",
    personalOperationsManagement: "What Is Personal Operations Management?",
    personalAssistantForExecutives: "Personal Assistant for Executives",
    ankoraVsPersonalAssistant: "Ankora vs. Personal Assistant",
    relatedReading: "Related reading",
    solutionsMenu: [
      { label: "Executives", blurb: "Focus your attention on what actually deserves it.", href: "/solutions/executives" },
      { label: "Founders", blurb: "Grow without carrying every operational detail alone.", href: "/solutions/founders" },
      { label: "Growing Companies", blurb: "Operational infrastructure that scales with you.", href: "/solutions/companies" },
      { label: "Family Offices", blurb: "One layer of management, full peace of mind.", href: "/solutions/family-office" },
    ],
  },
  hero: {
    eyebrow: "Operational Intelligence",
    title: "You run the business.\nWho runs everything else?",
    sub: "Ankora combines AI orchestration with dedicated human Operations Managers to remove the operational complexity of modern life — so you can focus on what matters.",
    ctaPrimary: "Book a Strategy Call",
    ctaSecondary: "How it works",
    definitionPre: "Ankora is a ",
    definitionLinked: "Personal Operations Management",
    definitionPost: " service for executives, founders and busy families. A dedicated human Operations Manager, backed by AI orchestration, takes end-to-end ownership of personal, household, vendor, administrative, travel and business operations.",
  },
  problem: {
    label: "The problem",
    title: "Your success requires hundreds of decisions a day.",
    body: "Not all of them need to go through you. Small tasks — an appointment, a renewal, a booking, a follow-up — don't take much time on their own. But they never disappear. They just move from tomorrow to tomorrow, taking up space you don't notice until it's gone.",
  },
  insight: {
    label: "The insight",
    title: "You don't need more time. You need fewer things to think about.",
    body: "Mental load, not lack of time, is what actually slows down high performers. Ankora was built to remove that layer entirely — not another tool to manage, but less to manage in the first place.",
  },
  category: {
    label: "A new category",
    title: "This isn't just a personal assistant. This is Operational Intelligence.",
    body: "Ankora combines AI orchestration with dedicated human Operations Managers to take full ownership of your operational complexity — not just complete tasks. We don't perform services. We buy back your time, attention, and peace of mind.",
  },
  howItWorks: {
    label: "How it works",
    title: "A process that disappears once it starts working",
    sub: "Five steps. None of them require you to manage them.",
    steps: [
      { title: "Request", body: "You share what needs to happen — in plain language, no forms, no long intake process." },
      { title: "Human Operations Manager", body: "A dedicated Operations Manager gets to know you, your preferences, and what matters to you." },
      { title: "AI Orchestration", body: "Our system coordinates, tracks, and follows up on what's needed — without being asked." },
      { title: "Execution", body: "The work is managed end to end, with full ownership, as if it were our own." },
      { title: "Proactive Update", body: "You hear from us before you have to ask — when things are on track, and when they're not." },
    ],
  },
  intelligence: {
    label: "Technology",
    title: "AI that remembers. People who decide.",
    body: "Our system remembers your preferences, schedules work, tracks progress, and flags what needs attention. Our Operations Managers bring judgment, empathy, and accountability — the parts AI shouldn't replace.",
    pillars: [
      { title: "Memory", body: "Every preference, every decision, always available — without repeating yourself." },
      { title: "Orchestration", body: "Many tasks, many parties, one transparent coordination layer." },
      { title: "Monitoring", body: "Continuous tracking of every open thread, so you don't have to check." },
      { title: "Prediction", body: "Flagging what needs attention before it becomes a problem." },
    ],
  },
  capabilities: {
    label: "Capabilities",
    title: "One operational layer, instead of a dozen open tabs",
    sub: "Every domain is owned by a dedicated Operations Manager, backed by AI orchestration.",
    items: [
      { title: "Personal Operations", body: "Your daily tasks, time, and commitments, managed in one place." },
      { title: "Vendor & Service Coordination", body: "Selection, coordination, and quality control across a vetted network." },
      { title: "Administrative Liaison", body: "Handling institutions and authorities on your behalf, start to finish." },
      { title: "Business Operations Support", body: "Ongoing operational support for small teams and growing companies." },
      { title: "Property & Household Operations", body: "Maintenance, coordination, and quality control for your home and property." },
      { title: "Travel & Logistics", body: "Planning, bookings, and changes — coordinated ahead of time." },
    ],
  },
  humanAI: {
    label: "Human + AI",
    title: "Not a replacement. A combination.",
    body: "Behind every task is a person. AI multiplies what they can do — it doesn't replace their accountability.",
    humanTitle: "Humans bring",
    human: ["Judgment", "Empathy", "Relationships", "Trust", "Decision-making"],
    aiTitle: "AI brings",
    ai: ["Memory", "Orchestration", "Automation", "Monitoring", "Prediction", "Documentation"],
  },
  industries: {
    label: "Who it's for",
    title: "Built for people whose time and attention are their most valuable resource",
    items: [
      { title: "Executives", body: "Focus on the decisions that actually require you.", href: "/solutions/executives" },
      { title: "Founders", body: "Grow without carrying every operational detail alone.", href: "/solutions/founders" },
      { title: "Growing Companies", body: "Operational infrastructure that scales with you, not against you.", href: "/solutions/companies" },
      { title: "Family Offices", body: "One management layer for the complexity of several lives.", href: "/solutions/family-office" },
    ],
  },
  trust: {
    label: "Trust",
    title: "Discretion is the default, not an add-on",
    body: "Every piece of information is handled in full confidentiality. Access is limited to those who genuinely need it, under a privacy policy built around the trust you place in us.",
    badges: ["Full privacy", "Registered Israeli business", "Human availability", "No long-term commitment"],
  },
  faq: {
    label: "FAQ",
    title: "Worth knowing before a call",
    items: [
      {
        q: "What is Personal Operations Management?",
        a: "Personal Operations Management is an operating model where an individual or family delegates ongoing operational ownership, not just isolated tasks. A dedicated Operations Manager, supported by AI orchestration, takes end-to-end responsibility for personal, household, vendor, administrative, travel and business operations, so nothing depends on you remembering, chasing or coordinating it yourself.",
      },
      {
        q: "How is Ankora different from a personal assistant?",
        a: "A personal assistant generally executes tasks you hand them. Ankora manages an operating layer: a dedicated Operations Manager takes full ownership of outcomes, is backed by AI orchestration with persistent memory of your preferences, and proactively surfaces what needs attention before you ask. Personal Assistant is a real and useful category — Ankora starts where it typically stops.",
      },
      {
        q: "How is Ankora different from a concierge service?",
        a: "Concierge services are typically request-based: you ask, they fulfill a specific, often one-off request. Ankora provides continuous, proactive ownership of recurring operational areas — personal, household, vendor, administrative, travel and business — tracked and followed through by the same dedicated Operations Manager over time, not handled as isolated requests to a rotating team.",
      },
      {
        q: "What types of tasks can Ankora manage?",
        a: "Personal administration and paperwork, household and property maintenance, vendor and service coordination, travel and logistics, appointments and renewals, dealings with authorities and institutions, and selected business operations support for founders and small teams. The full list of areas Ankora covers is on our Areas of Coverage page.",
      },
      {
        q: "Can Ankora manage both personal and business tasks?",
        a: "Yes. Many clients, particularly founders and executives, use Ankora for a mix of personal, household and business operational support. Your Operations Manager holds both sides in one place, rather than you managing separate assistants or vendors for each.",
      },
      {
        q: "Who actually executes the work?",
        a: "Your dedicated Operations Manager coordinates and oversees every task, often working with a vetted, quality-controlled vendor network for the physical or specialist work involved. You have one point of contact and one person accountable for the outcome, regardless of how many parties are involved behind the scenes.",
      },
      {
        q: "Do I get a dedicated Operations Manager?",
        a: "Yes. Every Ankora client is assigned a dedicated human Operations Manager who gets to know their preferences, standards and recurring needs over time. This continuity is what allows requests to get shorter and outcomes to get more predictable the longer we work together.",
      },
      {
        q: "What does the AI actually do?",
        a: "The AI layer maintains persistent memory of your preferences and history, orchestrates and tracks multiple open tasks at once, monitors deadlines and recurring obligations, and flags what needs attention before it becomes urgent. It supports the Operations Manager's judgment — it doesn't replace it.",
      },
      {
        q: "Does AI replace the human Operations Manager?",
        a: "No. AI handles memory, orchestration, monitoring and prediction — the parts of the work that benefit from consistency and scale. Judgment, empathy, relationships and accountability stay with your human Operations Manager. Ankora is built as a combination of the two, not a substitute of one for the other.",
      },
      {
        q: "Who is Ankora designed for?",
        a: "Executives, founders, entrepreneurs and busy professionals whose time and attention are their most valuable resource, as well as high-performing families managing significant operational complexity. Some Family Offices also use Ankora as an operational layer alongside their existing structure.",
      },
      {
        q: "Can Ankora coordinate with my existing vendors?",
        a: "Yes. Your Operations Manager can work with vendors, contractors and service providers you already use, alongside Ankora's own vetted network where a new provider is needed. Either way, coordination, scheduling and follow-through are handled on your behalf.",
      },
      {
        q: "How does Ankora handle recurring tasks?",
        a: "Recurring obligations — renewals, maintenance schedules, regular appointments — are tracked by the AI layer so they surface automatically ahead of time, rather than depending on you or us remembering. Your Operations Manager acts on them before they become time-sensitive.",
      },
      {
        q: "How does Ankora protect sensitive information?",
        a: "Privacy is the default, not an add-on. Information is handled in full confidentiality, access is limited to those who genuinely need it to complete the work, and nothing is shared beyond what's required, under a privacy policy built around the trust clients place in us.",
      },
      {
        q: "When would a full-time personal assistant be a better solution?",
        a: "If you need someone physically present with you for most of the working day, managing real-time scheduling changes in person, or handling tasks that require constant physical proximity, a full-time in-house Personal Assistant is often a better fit than an operational management service like Ankora.",
      },
      {
        q: "How do I get started?",
        a: "Book a short strategy call. We'll get to know you, map your operational footprint, and show you exactly how Ankora would work for your situation — no generic price lists, no long onboarding forms.",
      },
    ],
  },
  finalCta: {
    title: "Ready to put it down?",
    body: "A twenty-minute strategy call. No commitment, no long forms.",
    cta: "Book a call",
  },
  pages: {
    howItWorks: {
      eyebrow: "How it works",
      title: "One process. Zero management on your end.",
      sub: "From the first message, Ankora takes full ownership of what needs to happen.",
      blocks: [
        { title: "Request", body: "You share what needs to happen — a message, a call, a short note. No long forms, no questionnaires." },
        { title: "Intro call", body: "Your Operations Manager gets to know you, not just the task — what matters to you, what bothers you, which decisions you want us to make on your behalf." },
        { title: "Planning", body: "We research, compare, and bring you a clear recommendation — not a long list to sort through yourself." },
        { title: "Execution & AI orchestration", body: "The task is managed end to end. Our AI tracks it, follows up, and flags delays — so nothing falls through the cracks." },
        { title: "Proactive update & follow-up", body: "You hear from us at the moments that matter, not every small step. A few days after completion, we check that everything landed well." },
      ],
      vignette: {
        title: "One day, without you noticing",
        body: "A passport renewed, a vendor coordinated, a flight rebooked in time, a gift that arrived on the right day — four completely different tasks, coordinated by the same operational layer, without you having to remember any of them.",
      },
    },
    technology: {
      eyebrow: "Technology",
      title: "The layer that remembers you, so you don't have to explain again.",
      sub: "Our system isn't a chatbot executing commands. It's an orchestration layer connecting your request, your Operations Manager, and the execution network — with persistent memory that stays with you.",
      blocks: [
        { title: "Persistent memory", body: "Every preference you've shared, every decision you've made, is stored and used the next time — without repeating yourself." },
        { title: "Multi-party orchestration", body: "When a task touches several vendors or parties, the system coordinates between them and keeps information consistent everywhere." },
        { title: "Monitoring & prediction", body: "The system tracks every open thread and flags what's about to slip — before it becomes your problem." },
        { title: "A human in the loop, always", body: "Financial, sensitive, or exceptional decisions always go through a person. AI prepares — it doesn't decide for you." },
      ],
    },
    about: {
      eyebrow: "About",
      title: "We exist to give busy people back their most valuable resource.",
      sub: "Not time. Attention.",
      entityDefinition: "Ankora is an Israeli Personal Operations Management company. We give executives, founders and busy families a dedicated human Operations Manager, backed by AI orchestration, who takes end-to-end ownership of personal, household, vendor, administrative, travel and selected business operations. Ankora operates in Israel, serving clients across Tel Aviv and the surrounding area. This model, a human Operations Manager combined with AI orchestration and persistent operational memory, is what we call Operational Intelligence.",
      blocks: [
        { title: "Vision", body: "The world is full of small tasks that together create enormous mental load. We believe people shouldn't have to carry that load alone." },
        { title: "Mission", body: "To give people managing a lot — a business, a family, a career — one operational layer they can trust completely." },
      ],
      principlesLabel: "Our principles",
      principles: [
        { title: "Reliability above all", body: "If we committed to it, we deliver. If there's a delay, you hear it from us before you ask." },
        { title: "Full ownership", body: "Every task belongs to us until it's complete. There's no 'that's not my responsibility.'" },
        { title: "Initiative", body: "We don't wait to be asked. We think ahead, spot issues, and propose solutions." },
        { title: "Discretion", body: "We're trusted with your personal and business life. Every piece of information stays fully confidential." },
      ],
    },
    solutionsIndex: {
      eyebrow: "Who it's for",
      title: "One operational layer, matched to your kind of complexity",
      sub: "Four kinds of clients. The same principle: you focus on what matters, we manage everything else.",
    },
    roi: {
      eyebrow: "ROI Calculator",
      title: "How much time and money Ankora can give back",
      sub: "Pick the profile that fits you, adjust the numbers to your reality, and get an instant estimate.",
      personaPrompt: "Who are you?",
      hoursUnitLabel: "hours / week",
      hoursTotalLabel: "Total hours / week",
      rateNote: "This is the direct cost of the time. The system adds about 33% for employer overhead (pension, national insurance, benefits) to reflect the true fully-loaded cost.",
      nonProductiveLabel: "How much of that paid time is non-productive?",
      nonProductiveHint: "Sick days, vacation, breaks, and idle time. You pay for this today. You won't pay for it with Ankora.",
      nonProductiveDefault: 15,
      personas: [
        {
          key: "executives",
          hourQuestions: [
            { label: "Calendar, meetings, and appointment coordination", hint: "Personal and professional calendar, appointments", default: 2 },
            { label: "Dealing with authorities, national insurance, and banks", hint: "Tax authority, national insurance, bank", default: 1.5 },
            { label: "Business travel coordination and logistics", hint: "Flights, hotels, arrangements", default: 1.5 },
            { label: "Home and vehicle upkeep", hint: "Vendors, repairs, servicing", default: 2 },
            { label: "Paperwork, renewals, and documents", hint: "Passport, license, forms", default: 1 },
          ],
          rateLabel: "What's the direct hourly cost of your time?",
          rateHint: "Direct cost of your working hour, before employer overhead",
          rateDefault: 400,
        },
        {
          key: "founders",
          hourQuestions: [
            { label: "Coordinating vendors and service providers for the business", hint: "Inquiries, orders, follow-up", default: 2.5 },
            { label: "Bookkeeping and reporting to authorities", hint: "Reports, VAT, income tax", default: 2 },
            { label: "Ongoing personal admin", hint: "Bank, national insurance, health fund", default: 1.5 },
            { label: "Marketing and digital presence", hint: "Content, social media, campaigns", default: 2 },
            { label: "Home upkeep and personal errands", hint: "Vendors, repairs, arrangements", default: 1.5 },
          ],
          rateLabel: "What's the direct hourly cost of your time?",
          rateHint: "Direct cost of your working hour, before employer overhead",
          rateDefault: 350,
        },
        {
          key: "companies",
          hourQuestions: [
            { label: "Coordinating vendors and service providers", hint: "Selection, orders, quality control", default: 3 },
            { label: "Technical support and IT", hint: "Equipment, systems, issues", default: 2 },
            { label: "Procurement and office supplies", hint: "Orders, vendors, inventory", default: 2 },
            { label: "Admin with authorities and regulation", hint: "Licensing, reports, approvals", default: 2.5 },
            { label: "Organizing team travel and events", hint: "Flights, accommodation, logistics", default: 2.5 },
          ],
          rateLabel: "What's the direct hourly cost of whoever does this today?",
          rateHint: "You, an office manager, or a team member",
          rateDefault: 300,
        },
        {
          key: "familyOffice",
          hourQuestions: [
            { label: "Coordinating vendors and service providers", hint: "Selection, coordination, quality control", default: 2 },
            { label: "Dealing with authorities and banks", hint: "Tax authority, national insurance, bank", default: 1.5 },
            { label: "Ongoing admin and paperwork", hint: "Documents, renewals, forms", default: 1.5 },
            { label: "Office and equipment upkeep", hint: "Equipment, IT, repairs", default: 1.5 },
            { label: "Meeting and logistics coordination", hint: "Calendar, travel, events", default: 1.5 },
          ],
          rateLabel: "What's the direct hourly cost of whoever does this today?",
          rateHint: "You, or a team member",
          rateDefault: 250,
        },
      ],
      results: {
        title: "Your estimate",
        hoursFreedLabel: "Hours freed per month",
        valueFreedLabel: "Full employer cost of the time spent today",
        valueFreedHint: "The direct hourly cost you entered, plus about 33% employer overhead and non-productive paid time",
        costLabel: "Estimated Ankora cost",
        costHint: "Based on an example rate of $35/hour",
        netValueLabel: "Net monthly savings",
        multipleLabel: "A return of",
        multipleSuffix: "on every dollar spent",
        ctaBody: "These numbers are an estimate. A short intro call will give you an exact picture.",
        cta: "Book an intro call",
        footnote: "* This calculation is illustrative only: the cost of time spent today is the direct hourly cost entered, multiplied by 1.33 to reflect employer overhead, then divided by the productive share of paid time (100% minus the non-productive percentage entered). Ankora's cost is based on an example rate of $35/hour. It does not constitute a price quote or commitment.",
      },
      hiddenCost: {
        label: "Beyond the numbers",
        title: "There's also a cost to what doesn't get handled",
        body: "The calculator above measures what can be counted: hours and money. But part of the real cost of operational overload doesn't show up in a table.",
        items: [
          {
            title: "Financial",
            body: "A late fee on a bill that slipped, interest on a debt that was forgotten, a small repair that became a big one because it was postponed.",
          },
          {
            title: "Opportunity",
            body: "A call that wasn't returned in time, a vendor that never got aligned, a decision delayed because no one handled the details around it.",
          },
          {
            title: "Personal",
            body: "The mental load that stays with you after the workday ends, and the attention that gets split between what's urgent and what actually matters.",
          },
        ],
      },
    },
    pricing: {
      eyebrow: "Pricing",
      title: "You pay for time worked. Not for a headcount.",
      sub: "Ankora's pricing model means you pay only for time that actually worked for you, with no hidden costs and no long-term commitment.",
      billing: {
        label: "How it's measured",
        title: "You pay only for the time we worked for you",
        body: "No sick days, no vacation, no lunch breaks, no idle time. Every minute of actual work is tracked and reported transparently.",
        points: [
          { title: "Tracked to the minute", body: "Every task is logged precisely, with no rounding up." },
          { title: "15-minute minimum", body: "A small task gets a small charge, not a full hour." },
          { title: "Only actual work time", body: "No charge for waiting time, sick days, or vacation, unlike direct employment." },
        ],
      },
      costCompare: {
        label: "The real cost of hiring",
        title: "The price you pay is the full price",
        body: "With an in-house hire, salary is just the start. Pension, vacation, sick days, a training fund, national insurance, recruiting, training, and workspace all add to the real cost. With Ankora, the hourly rate covers everything.",
        inHouseTitle: "In-house hire",
        inHouseItems: ["Base salary", "Pension contributions", "Vacation and sick days", "Training fund", "Employer national insurance", "Recruiting, training, and management"],
        ankoraTitle: "Ankora",
        ankoraItems: ["Only actual hours worked", "No added costs", "No long-term commitment"],
      },
      hourBank: {
        label: "The structure",
        title: "An hour bank that renews with you",
        body: "You purchase an hour bank upfront, every month. Didn't use all your hours? They roll over to next month, as long as the plan renews.",
        points: [
          { title: "Unused hours roll over", body: "As long as you keep renewing, nothing goes to waste." },
          { title: "No long-term commitment", body: "You can pause the plan any month, no penalty, no explanation needed." },
        ],
      },
      tiers: {
        label: "Packages",
        title: "The larger the hour bank, the better the hourly rate",
        sub: "Three illustrative examples. Scope and fit are set during the intro call.",
        items: [
          { name: "Starter", hours: "10 hours / month", rate: "$50 / hour", blurb: "For focused operational needs.", highlighted: false },
          { name: "Ongoing", hours: "20 hours / month", rate: "$44 / hour", blurb: "For steady, ongoing operational management.", highlighted: true },
          { name: "Extended", hours: "40 hours / month", rate: "$38 / hour", blurb: "For complex, multi-area operational load.", highlighted: false },
        ],
        footnote: "* Figures are illustrative only and do not constitute a price quote. Final pricing is set according to scope during the intro call.",
      },
      closing: {
        title: "Ready to see how much time this actually saves?",
        body: "A twenty-minute intro call. No commitment, no long forms.",
        cta: "Book an intro call",
      },
    },
    contact: {
      eyebrow: "Book a call",
      title: "Let's talk for twenty minutes",
      sub: "No commitment, no long forms. We'll get to know you, understand your needs, and show you how Ankora could work for you.",
      nameLabel: "Full name",
      emailLabel: "Email",
      companyLabel: "Company (optional)",
      messageLabel: "How can we help?",
      submit: "Send & book a call",
      directTitle: "Or directly",
      directBody: "Write to us and we'll respond within one business day.",
      successMessage: "Thank you! We've received your message and will get back to you soon.",
      errorMessage: "Something went wrong sending this. Please try again, or email us directly at info@ankora.co.il.",
    },
    legal: {
      privacyTitle: "Privacy Policy",
      termsTitle: "Terms of Use",
      placeholder: "For privacy or data security questions, please contact us directly at info@ankora.co.il.",
      termsPlaceholder: "The terms governing use of this site and Ankora’s services.",
      updated: "Last updated: August 2026",
      privacySections: [
        {
          title: "Overview",
          body: "Ankora (\"the company\", \"we\") operates an operational management platform combining human oversight with AI. This policy explains what information we collect, how it is used, and how it is stored and protected.",
        },
        {
          title: "Information we collect",
          body: "Contact details (name, phone, email), the content of requests submitted to us, and operational information required to carry out defined tasks, including calendar details, preferences, and relevant correspondence shared with us.",
        },
        {
          title: "How information is used",
          body: "Information is used to operate the service, personalize it to each client's needs, coordinate with external parties on the client's behalf, and continuously improve service quality. It is never used for purposes unrelated to the service without explicit consent.",
        },
        {
          title: "Sharing with third parties",
          body: "Information is shared with external providers only to the extent required to complete a specific requested task, and only after those providers have been vetted. Ankora does not sell, rent, or transfer personal information for third-party marketing purposes.",
        },
        {
          title: "Data security",
          body: "We apply industry-standard technical and organizational safeguards, including restricted access permissions, encryption in transit and at rest, and confidentiality commitments from all staff and authorized providers.",
        },
        {
          title: "Retention and your rights",
          body: "Information is retained for as long as needed to provide the service and comply with legal requirements. You may contact us at any time to review, correct, or delete your information.",
        },
        {
          title: "Cookies and analytics",
          body: "The site makes limited use of basic analytics tools to understand and improve usage. Cookies can be blocked through your browser settings without affecting the site's functionality.",
        },
        {
          title: "Contact",
          body: "For questions about this policy or the personal information we hold, please contact us at info@ankora.co.il.",
        },
      ],
      termsSections: [
        {
          title: "General",
          body: "Use of this site and Ankora's services is subject to the terms below. Using the site or requesting an intro call constitutes acceptance of these terms.",
        },
        {
          title: "The service",
          body: "Ankora provides an operational management layer that combines a dedicated human operations manager with technology that supports coordination, tracking, and follow-up. The service does not make financial, legal, or medical decisions on a client's behalf, and is not a substitute for professional advice in those areas.",
        },
        {
          title: "Getting started",
          body: "Engagements begin with an intro call to assess fit, after which scope and commercial terms are agreed individually. There is no long-term commitment, and either party may end the engagement per the terms agreed between them.",
        },
        {
          title: "Client responsibilities",
          body: "Clients are responsible for providing accurate, up-to-date information and any access required to carry out defined tasks. Ankora acts based on the information and instructions provided by the client.",
        },
        {
          title: "Limitation of liability",
          body: "Ankora takes reasonable care in selecting external providers but is not liable for their failures beyond that reasonable vetting. The service is provided \"as is\", and nothing here extends Ankora's liability beyond what is required by law.",
        },
        {
          title: "Confidentiality and IP",
          body: "All information shared as part of an engagement is treated as strictly confidential. All content, design, and technology on this site are the property of Ankora and may not be used without prior written permission.",
        },
        {
          title: "Governing law",
          body: "These terms are governed exclusively by the laws of the State of Israel, and the competent courts of the Tel Aviv district shall have exclusive jurisdiction.",
        },
        {
          title: "Contact",
          body: "For questions about these terms, please contact us at info@ankora.co.il.",
        },
      ],
    },
    segments: {
      executives: {
        eyebrow: "Executives",
        title: "Focus on the decisions that actually require you.",
        sub: "Your success requires hundreds of decisions a day. Not all of them need to go through you.",
        bullets: [
          { title: "Time & commitment management", body: "A calendar, reminders, and follow-up that don't require you to remember." },
          { title: "Administrative liaison", body: "With authorities, banks, and institutions — without you standing in line." },
          { title: "Personal & family coordination", body: "Handled separately, without spilling into your business day." },
        ],
        closing: "One Operations Manager who knows your pace.",
      },
      founders: {
        eyebrow: "Founders",
        title: "Grow without carrying every operational detail alone.",
        sub: "In the early stages you do everything. Ankora gives you an operational layer without hiring another role.",
        bullets: [
          { title: "Ongoing operations", body: "What steals time from product and team gets managed elsewhere." },
          { title: "Vendor coordination", body: "From a vetted network, without burning time on comparisons." },
          { title: "Full flexibility", body: "Scales up and down with what the company needs right now." },
        ],
        closing: "Operational infrastructure that grows with you.",
      },
      companies: {
        eyebrow: "Growing Companies",
        title: "Operational infrastructure that scales with you, not against you.",
        sub: "Fast growth creates operational complexity no job description covers.",
        bullets: [
          { title: "Ongoing operational support", body: "For small teams that need more without hiring more." },
          { title: "Vendor & procurement management", body: "Comparison, coordination, and quality control in one place." },
          { title: "Reporting & clarity", body: "See what's in progress, what's done, and what needs attention." },
        ],
        closing: "An operational layer you can trust while growing fast.",
      },
      familyOffice: {
        eyebrow: "Family Offices",
        title: "One management layer for the complexity of several lives.",
        sub: "Several properties, several family members, dozens of vendors — one place managing all of it.",
        bullets: [
          { title: "Property operations", body: "Maintenance, vendors, and quality control across several properties at once." },
          { title: "Family coordination", body: "Events, travel, and commitments — coordinated with full transparency." },
          { title: "Absolute discretion", body: "Limited access, full documentation, confidentiality by default." },
        ],
        closing: "Peace of mind that covers more than one domain.",
      },
    },
    coverage: {
      eyebrow: "Areas of coverage",
      title: "Ankora's areas of operation",
      sub: "Anything that creates operational load has one address.",
      intro: "The list below is a sample of what we manage for our clients. If something isn't listed here, ask us anyway.",
      searchPlaceholder: 'Search by keyword, like "car" or "authorities"',
      searchNoResults: "No results found. Try another word, or just ask us.",
      categories: [
        {
          name: "With Authorities & Institutions",
          description: "Coordination, applications and follow-up with government offices, national insurance, banks, health funds and local authorities.",
          services: [
            { name: "Health fund liaison", description: "Booking appointments, checking eligibility and filing requests with the health fund, start to finish." },
            { name: "Passport renewal", description: "Booking the appointment, preparing documents and guiding you through the renewal." },
            { name: "Driver's license renewal", description: "Checking eligibility, completing the application and booking the appointment." },
            { name: "Form filling", description: "Accurate completion of forms for public and private bodies." },
            { name: "Appointment scheduling", description: "Booking, changing and canceling appointments with public and private bodies, tracked to close." },
            { name: "Government application filing", description: "Preparing and filing applications with government offices as needed." },
            { name: "National insurance liaison", description: "Filing forms, tracking requests and booking appointments with National Insurance." },
            { name: "Tax authority liaison", description: "Filing requests, coordinating meetings and following up with the tax authority." },
            { name: "Bank liaison", description: "Coordinating meetings, gathering documents and full support at the bank." },
            { name: "Insurance company liaison", description: "Filing documents, tracking a claim and coordinating meetings with the insurer." },
            { name: "Municipality liaison", description: "Filing requests, coordinating meetings and following up with the local authority." },
          ],
        },
        {
          name: "Electrical, AC & Home Security",
          description: "Installation, repair and maintenance of electrical, air conditioning and security systems.",
          services: [
            { name: "Electrical panel replacement", description: "Replacing the home's electrical panel, with a full safety check on completion." },
            { name: "Outlet replacement", description: "Replacing an existing electrical outlet with a certified one." },
            { name: "Light fixture installation", description: "Removing an old fixture and installing a new one, with a function check." },
            { name: "Ceiling fan installation", description: "Installing and wiring a ceiling fan, including balance and function checks." },
            { name: "Electrical short repair", description: "Locating and fixing an electrical fault and restoring safe operation." },
            { name: "Alarm system installation", description: "Full alarm system installation, from control panel to app." },
            { name: "Security camera installation", description: "Supply, installation and network setup of security cameras." },
            { name: "AC installation", description: "Full supply and installation of an air conditioner, including gas and wiring." },
            { name: "AC cleaning", description: "Routine cleaning and maintenance to keep the AC performing well." },
            { name: "AC repair", description: "Diagnosing and fixing faults in the cooling system." },
          ],
        },
        {
          name: "Plumbing, Locks & Assembly",
          description: "Plumbing repairs, bathroom and kitchen fixtures, locks and furniture assembly.",
          services: [
            { name: "Furniture assembly", description: "Assembling furniture at home per manufacturer instructions, including wall anchoring by agreement." },
            { name: "TV mounting", description: "Mounting a screen on a wall or stand and connecting the equipment." },
            { name: "Furniture disassembly & reassembly", description: "Taking furniture apart and reassembling it for a move." },
            { name: "Picture hanging", description: "Hanging pictures, mirrors and light shelves at home." },
            { name: "Toilet replacement", description: "Removing the old toilet and installing a new one, with a leak check." },
            { name: "Toilet installation", description: "Installing a new toilet and connecting it to water and drainage." },
            { name: "Faucet replacement", description: "Removing the old faucet and installing a new one, with a seal check." },
            { name: "Kitchen faucet installation", description: "Installing a kitchen faucet, including connection and a function check." },
            { name: "Sink installation", description: "Installing a new sink and connecting it to water and drainage." },
            { name: "Drain unclogging", description: "Locating and clearing blockages in drainage systems." },
            { name: "Sewer unclogging", description: "Clearing sewer line blockages mechanically or with pressure flushing." },
            { name: "Leak repair", description: "Locating and fixing the source of a leak, including parts and seals." },
            { name: "Solar water heater installation", description: "Supply and installation of a solar water heater and collectors." },
            { name: "Solar water heater repair", description: "Diagnosing and repairing faults in the solar heating system." },
            { name: "Cylinder lock replacement", description: "Removing the old lock cylinder and installing a new one, with a function check." },
            { name: "Lock installation", description: "Installing a new lock or replacing the locking mechanism on a door." },
            { name: "Lockout service", description: "Opening a locked door using professional tools." },
          ],
        },
        {
          name: "Garden & Outdoors",
          description: "Ongoing garden upkeep, irrigation and outdoor care.",
          services: [
            { name: "Tree pruning", description: "Pruning, shaping and care of tree branches." },
            { name: "Irrigation system installation", description: "Planning and installing a garden irrigation system." },
            { name: "Lawn mowing", description: "Mowing the lawn and clearing plant debris." },
            { name: "Garden maintenance", description: "Ongoing garden care: mowing, pruning, feeding, seasonal planting and irrigation." },
          ],
        },
        {
          name: "Home Cleaning",
          description: "Routine and deep cleaning for the home, the office, and every stage of a move.",
          services: [
            { name: "Routine cleaning", description: "Regular cleaning of the home or office, including kitchen and bathrooms." },
            { name: "Deep cleaning", description: "Thorough cleaning including windows, cabinets and kitchen, with a full scrub." },
            { name: "Pre-move-in cleaning", description: "Deep cleaning of the home before moving in." },
            { name: "Window cleaning", description: "Cleaning accessible windows, frames and blinds." },
            { name: "Upholstery cleaning", description: "Professional cleaning of sofas and upholstery based on fabric type." },
            { name: "Carpet cleaning", description: "Cleaning carpets at home or offsite by vacuuming, washing or steam." },
            { name: "Post-renovation cleaning", description: "Clearing dust and debris from the space after renovation work." },
            { name: "Pre-handover cleaning", description: "Full cleaning before handing over a new or renovated home." },
            { name: "Floor polishing", description: "Polishing and protecting stone, marble or terrazzo floors." },
          ],
        },
        {
          name: "Renovation & Finishing",
          description: "Limited-scope renovation, painting and finishing work inside the home.",
          services: [
            { name: "Apartment painting", description: "Painting walls, ceilings and frames, including surface prep." },
            { name: "Bathroom renovation", description: "Bathroom renovation: demolition, tiling, fixtures and finishes." },
            { name: "Room renovation", description: "Renovating an existing room: paint, drywall, flooring and finishes." },
            { name: "Kitchen renovation", description: "Kitchen renovation: cabinets, countertops, tiling and plumbing." },
            { name: "Drywall repair", description: "Patching holes and cracks and replacing drywall panels." },
            { name: "Paint touch-ups", description: "Local wall and ceiling touch-ups, including filler and paint." },
          ],
        },
        {
          name: "Health & Wellbeing",
          description: "Administrative and logistical support around medical care.",
          services: [
            { name: "At-home blood test", description: "Drawing blood samples at home and delivering them to the lab." },
            { name: "Medical equipment rental", description: "Renting home medical equipment, from a care bed to a walker." },
            { name: "Specialist appointment booking", description: "Finding the right specialist, booking the appointment and tracking availability." },
            { name: "Doctor house call", description: "A doctor visiting your home for examination, diagnosis and prescriptions." },
            { name: "Medical appointment escort", description: "Physical and logistical support to and through a medical appointment." },
            { name: "Elder caregiver matching", description: "Finding, screening and coordinating a suitable caregiver." },
          ],
        },
        {
          name: "Family, Events & Pets",
          description: "Managing family moments, small events and pet care.",
          services: [
            { name: "Event photography", description: "Stills and video for private or business events, including editing." },
            { name: "Catering", description: "Preparing, transporting and serving food for events." },
            { name: "Dog walking", description: "Walking and exercising dogs per the owner's instructions." },
            { name: "Pet boarding", description: "Hosting, supervising and feeding pets on a day-to-day basis." },
            { name: "Private tutoring", description: "Private lessons, tutoring and exam preparation." },
            { name: "Family events (birthdays)", description: "Planning, coordinating and hosting small family events." },
            { name: "Family vacation planning", description: "Building an itinerary, comparing lodging and flights, and managing the schedule." },
            { name: "Pet sitter matching", description: "Finding and coordinating a suitable pet sitter." },
            { name: "Kid pickup", description: "Picking a child up from school or an activity and delivering them safely." },
            { name: "Babysitter matching", description: "Finding and coordinating a babysitter to fit the family's needs." },
          ],
        },
        {
          name: "Moving & Logistics",
          description: "Packing, storage and moving at every stage.",
          services: [
            { name: "Storage", description: "Short or long-term storage of household contents." },
            { name: "Home packing", description: "Packing up the home ahead of a move or storage, including materials." },
            { name: "Home moving", description: "Moving household contents from one property to another, loading to setup." },
          ],
        },
        {
          name: "Finance, Insurance & Pension",
          description: "Advice and support managing money, insurance and retirement savings.",
          services: [
            { name: "Investment advice", description: "Professional recommendations on investing in securities and financial instruments." },
            { name: "Financial statement audit", description: "Independent audit of financial statements and an opinion on their fairness." },
            { name: "Tax refund", description: "Checking eligibility and filing a tax refund request." },
            { name: "Business bookkeeping", description: "Managing the business's books, bank reconciliations and periodic reports." },
            { name: "Tax advice", description: "Tax planning, reviewing liabilities and preparing filings." },
            { name: "Annual tax filing", description: "Preparing and filing the annual return with the tax authority." },
            { name: "Mortgage advice", description: "Comparing tracks and offers and guiding you through the loan process." },
            { name: "Pension advice", description: "Matching pension products to your personal needs." },
            { name: "Insurance advice", description: "Matching coverage to your needs, independent of any one insurer." },
            { name: "Duplicate insurance check", description: "Finding duplicate or unnecessary coverage in existing policies." },
            { name: "Duplicate pension fund check", description: "Finding duplicate holdings across pension, provident and training funds." },
            { name: "Retirement planning", description: "Building a retirement plan: income, pensions and taxation." },
          ],
        },
        {
          name: "Legal & Personal Documentation",
          description: "Drafting documents, advice and legal representation across personal matters.",
          services: [
            { name: "Legal advice", description: "Legal opinions, advice and drafting of legal documents." },
            { name: "Notary services", description: "Verifying, certifying and preparing notarized documents." },
            { name: "Prenuptial agreement", description: "Preparing an agreement governing a couple's financial affairs." },
            { name: "Enduring power of attorney", description: "Preparing an enduring power of attorney and filing it with the state guardian." },
            { name: "Will drafting", description: "Preparing a will in line with the testator's wishes and the law." },
            { name: "Employment contract", description: "Drafting an employment contract in line with labor law." },
            { name: "Lease agreement", description: "Drafting a residential or commercial lease." },
            { name: "Mediation", description: "Running a mediation process to reach agreement outside of court." },
            { name: "Court representation", description: "Legal representation in court and tribunal proceedings." },
          ],
        },
        {
          name: "Real Estate & Business Setup",
          description: "Support through property deals, company formation and rental management.",
          services: [
            { name: "Real estate brokerage", description: "Matching buyers and sellers or landlords and tenants, including property search." },
            { name: "Property appraisal", description: "Valuing a property for deals, mortgages or legal proceedings." },
            { name: "Company formation", description: "Full support setting up a company, from incorporation documents to the registrar." },
            { name: "Sole proprietor registration", description: "Registering with VAT, income tax and National Insurance." },
            { name: "Home sale support", description: "Coordinating between lawyer, broker and bank, and tracking the process." },
            { name: "Home purchase support", description: "Full administrative support through the purchase process." },
            { name: "Company dissolution", description: "Support through voluntary company dissolution with the authorities." },
            { name: "Rental property management", description: "Finding tenants, handling issues and overseeing the property." },
            { name: "Property valuation", description: "Valuing a property for a sale, purchase or rental decision." },
          ],
        },
        {
          name: "Travel",
          description: "Planning and booking every part of a trip, for business and leisure.",
          services: [
            { name: "Flight booking", description: "Comparing, booking and managing changes to flights." },
            { name: "Hotel booking", description: "Finding, comparing and booking accommodation." },
            { name: "Car rental", description: "Comparing, booking and coordinating pickup and return of a rental car." },
            { name: "Travel insurance", description: "Matching and purchasing travel insurance for a trip abroad." },
            { name: "Visa application", description: "Preparing documents and filing a visa application." },
            { name: "Trip itinerary planning", description: "Personal trip planning, from attractions to lodging." },
            { name: "Business trip planning", description: "Coordinating flights, lodging, transport and meetings for a work trip." },
          ],
        },
        {
          name: "Technology & IT",
          description: "Support, maintenance and management of computing systems.",
          services: [
            { name: "Data backup", description: "Planning and setting up a backup system for your digital data." },
            { name: "Managed IT services", description: "Support, maintenance and management of computing systems and infrastructure." },
            { name: "Technical support", description: "Remote or on-site troubleshooting, software installs and user guidance." },
          ],
        },
        {
          name: "Business, Branding & Content",
          description: "Building the business's presence and content, from branding to campaigns.",
          services: [
            { name: "Business branding", description: "Developing a brand identity: strategy, values and voice." },
            { name: "Logo design", description: "Designing a logo and basic visual identity for a business." },
            { name: "Presentation design", description: "Building a business or marketing presentation tailored to your needs." },
            { name: "Document translation", description: "Translating personal, business or technical documents." },
            { name: "Website build", description: "Planning, designing and building a full website." },
            { name: "Social media management", description: "Content creation, posting and ongoing engagement on social media." },
            { name: "Office supplies procurement", description: "Sourcing vendors and ordering office supplies." },
            { name: "Content writing", description: "Writing marketing content, articles and website copy." },
            { name: "Video editing", description: "Professional video editing for ads, training or personal use." },
            { name: "Brand photography", description: "Professional photography of people, teams and products for branding." },
            { name: "Ad campaign management", description: "Planning, launching and managing an advertising campaign." },
          ],
        },
        {
          name: "Vehicle Care",
          description: "Cleaning, periodic maintenance and everyday vehicle care.",
          services: [
            { name: "Detailing", description: "Professional cleaning, restoration and protection for your car, including polish and coatings." },
            { name: "Interior cleaning", description: "Deep cleaning of the car's interior: seats, carpets and dashboard." },
            { name: "Car wash", description: "Basic exterior and interior car cleaning." },
            { name: "Towing", description: "Towing a car from the breakdown or accident site to where it's needed." },
            { name: "Battery replacement", description: "Removing the old battery and installing a new one, with a start check." },
            { name: "Tire replacement", description: "Removing and installing a new tire, including wheel balancing." },
            { name: "Periodic service", description: "Manufacturer-schedule maintenance: oil, filters and safety checks." },
            { name: "Flat tire repair", description: "Locating and repairing a puncture, or replacing the tire if needed." },
          ],
        },
        {
          name: "Vehicle Buying, Selling & Licensing",
          description: "Full support through a vehicle deal and any process with the licensing authority.",
          services: [
            { name: "Pre-purchase vehicle inspection", description: "A professional check of the car's condition before you buy." },
            { name: "Car sale support", description: "Support selling a car: listing, buyers and ownership transfer." },
            { name: "Car purchase support", description: "Support buying a new or used car, from search to closing." },
            { name: "Annual roadworthiness test", description: "Driving the car to the test center and handling the annual test." },
            { name: "Vehicle license renewal", description: "Renewing the vehicle license with the transport ministry, including fees." },
            { name: "Vehicle licensing", description: "Handling vehicle licensing processes with the transport ministry." },
          ],
        },
      ],
    },
    personalOperationsManagement: {
      eyebrow: "Personal Operations Management",
      title: "What Is Personal Operations Management?",
      sub: "An operating model for people who need to delegate ownership, not just tasks.",
      directAnswerLabel: "In short",
      directAnswer: "Personal Operations Management is an operating model in which an individual or family delegates ongoing operational ownership, not just isolated tasks, to a dedicated Operations Manager backed by AI orchestration. Instead of coordinating vendors, appointments, paperwork and follow-ups yourself, one person takes end-to-end responsibility for the outcome, across your personal, household, administrative, travel and selected business operations.",
      problem: {
        title: "The problem isn't the amount of work",
        intro: "Most operational tasks are individually small. The difficulty is everything they touch:",
        items: [
          "Personal administration and paperwork",
          "Household and property upkeep",
          "Vendors and service providers",
          "Maintenance and repairs",
          "Travel and logistics",
          "Appointments and renewals",
          "Bureaucracy and institutions",
          "Recurring obligations",
          "Business operations support",
          "Follow-ups on things already in motion",
          "Open loops nobody officially owns",
        ],
        closing: "None of these take much time on their own. The cost is having to remember, coordinate, chase and manage all of them at once, indefinitely.",
      },
      whatManagerDoes: {
        title: "What a Personal Operations Manager does",
        body: "A Personal Operations Manager takes end-to-end ownership of a task or area, not just the visible step. That means identifying what needs to happen, coordinating the people involved, tracking it to completion, and handling whatever goes wrong along the way, without it coming back to you as a decision you need to make.",
        examples: [
          { title: "A home repair", body: "Ankora identifies the appropriate provider, coordinates availability, confirms the appointment, manages communication, follows the repair through completion, handles outstanding issues, and keeps you updated, without you managing the process." },
          { title: "A recurring renewal", body: "A license, subscription or permit is tracked ahead of its deadline, renewed proactively, and confirmed, so it never becomes an urgent problem." },
          { title: "A trip with moving parts", body: "Flights, accommodation and ground logistics are planned and booked together, monitored for changes, and adjusted in real time if something shifts." },
        ],
      },
      comparisonPA: {
        title: "Personal Operations Manager vs. Personal Assistant",
        intro: "Both are valuable. They solve different problems.",
        columnA: "Personal Assistant",
        columnB: "Personal Operations Manager",
        rows: [
          { dimension: "Primary unit of work", a: "Individual tasks you assign", b: "Ongoing areas of responsibility" },
          { dimension: "Ownership", a: "Executes what's requested", b: "Owns the outcome end-to-end" },
          { dimension: "Memory of preferences", a: "Depends on the individual", b: "Persistent, supported by AI orchestration" },
          { dimension: "Follow-through", a: "Typically ends once the task is done", b: "Continues until the issue is fully resolved" },
          { dimension: "Proactivity", a: "Generally responds to requests", b: "Surfaces what needs attention before you ask" },
          { dimension: "Coverage", a: "Tied to one person's availability", b: "Backed by a team and AI monitoring" },
          { dimension: "Scope", a: "Often personal or admin-focused", b: "Personal, household, vendor, admin, travel and business" },
        ],
      },
      comparisonConcierge: {
        title: "Personal Operations vs. Concierge",
        intro: "Concierge services are excellent at fulfilling specific requests. Personal Operations Management is built for continuity.",
        columnA: "Concierge",
        columnB: "Personal Operations Management",
        rows: [
          { dimension: "Model", a: "Request-based, one-off fulfillment", b: "Ongoing, proactive ownership" },
          { dimension: "Relationship", a: "Often a rotating team", b: "One dedicated Operations Manager" },
          { dimension: "Memory", a: "Limited to the current request", b: "Persistent across every interaction" },
          { dimension: "Typical use case", a: "A restaurant booking, an event, a one-time request", b: "Recurring operational areas of your life or business" },
          { dimension: "Follow-up", a: "Usually not included", b: "Built into the model" },
        ],
      },
      humanAI: {
        title: "Why human plus AI, not one or the other",
        body: "An Operations Manager brings judgment, empathy, relationships and accountability, the parts of the work that require a person. AI brings persistent operational memory, orchestration across multiple open tasks, monitoring of deadlines and recurring obligations, and early identification of open loops before they become urgent. Neither replaces the other.",
        points: [
          { title: "Persistent memory", body: "Your preferences, history and standards are retained and applied automatically, not re-explained each time." },
          { title: "Orchestration", body: "Multiple tasks and parties are coordinated in parallel, on one visible timeline." },
          { title: "Monitoring", body: "Every open item is tracked continuously, so nothing depends on someone remembering to check." },
          { title: "Follow-up", body: "Tasks are followed through to actual completion, including anything that goes wrong along the way." },
        ],
      },
      whoFor: {
        title: "Who it's for",
        items: [
          "CEOs and senior executives",
          "Founders and entrepreneurs",
          "Busy professionals managing significant complexity",
          "High-performing families",
          "Family Offices, as an operational layer alongside their existing structure",
        ],
      },
      examples: {
        title: "What this looks like in practice",
        items: [
          { scenario: "A plumbing issue at home", shallow: "\"Ankora finds a plumber.\"", deep: "Ankora identifies the appropriate provider, coordinates availability, confirms the appointment, manages communication, follows the repair through completion, handles outstanding issues, and keeps you updated, without you managing the process." },
          { scenario: "A passport renewal", shallow: "\"Ankora books an appointment.\"", deep: "Ankora tracks the expiry date ahead of time, prepares the required documents, books and manages the appointment, and confirms the new passport is issued and delivered." },
          { scenario: "A recurring vendor, like a gardener or cleaner", shallow: "\"Ankora hires someone.\"", deep: "Ankora selects and vets the provider, sets the recurring schedule, monitors quality over time, and handles any issue or replacement without you needing to manage the relationship." },
        ],
      },
      notRightFit: {
        title: "When Personal Operations Management is not the right solution",
        body: "This model isn't for everyone, and it shouldn't be presented as if it were.",
        items: [
          "You need someone physically present with you for most of the working day",
          "The work is primarily hands-on, in-person execution rather than coordination",
          "You want a single employee under your direct daily management, rather than a managed service",
        ],
      },
      faq: [
        { q: "Is Personal Operations Management the same as a virtual assistant service?", a: "No. Virtual assistant services typically execute discrete tasks remotely, often through different people each time. Personal Operations Management assigns one dedicated person to own an area of your life or business continuously, backed by AI orchestration that retains context between every interaction." },
        { q: "Do I need to manage my Operations Manager?", a: "No. The point of the model is that you don't manage the process, only the outcome. Your Operations Manager identifies what needs to happen and follows it through; you're updated proactively rather than asked to check in." },
        { q: "What happens if something goes wrong with a vendor or provider?", a: "It stays your Operations Manager's responsibility to resolve, not yours. Handling issues, delays and unsatisfactory work is part of end-to-end ownership, not a separate request you need to raise." },
        { q: "Can Personal Operations Management replace an in-house employee?", a: "For most operational and administrative needs, yes. For roles that require someone physically present with you throughout the day, an in-house Personal Assistant is usually a better fit. Many clients use both models for different parts of their life." },
        { q: "How is pricing structured?", a: "Engagements are scoped to your operational footprint rather than sold as a fixed generic package. Details are on our pricing page." },
        { q: "Is this only for individuals, or also for families?", a: "Both. Many clients use Ankora for their personal and professional operations, others use it primarily to manage household and family operations, and some use it for a combination of the two." },
        { q: "Does Ankora work with vendors I already use?", a: "Yes. Your Operations Manager can coordinate with your existing vendors and providers, and bring in vetted alternatives from Ankora's network only where needed." },
        { q: "What makes AI orchestration different from a general AI assistant?", a: "A general AI assistant responds to prompts. Ankora's AI orchestration works continuously in the background, maintaining memory of your operational context, tracking multiple open items, and prompting your human Operations Manager to act, rather than requiring you to prompt it yourself." },
        { q: "How quickly can Ankora start managing something new?", a: "Once an area is scoped with your Operations Manager, most recurring operational areas can be picked up within days. Time-sensitive requests are handled as they arise." },
        { q: "Where does Ankora operate?", a: "Ankora is based in Israel and currently serves clients in Tel Aviv and the surrounding area." },
      ],
      ctaTitle: "See if Personal Operations Management fits how you work",
      ctaBody: "A short strategy call is the fastest way to find out.",
      cta: "Book a Strategy Call",
    },
    personalAssistantForExecutives: {
      eyebrow: "Personal Assistant for Executives",
      title: "Looking for a Personal Assistant? You May Need More Than an Assistant.",
      sub: "What a Personal Assistant typically covers, and where executives often need something broader.",
      directAnswer: "Most executives who search for a Personal Assistant are really looking for relief from operational complexity, not just a calendar manager. A traditional PA is an excellent solution for scheduling, correspondence and day-to-day support. When personal, household, vendor, administrative and business operations start overlapping, many executives find they need broader ownership than a single assistant, however capable, can provide alone.",
      expectations: {
        title: "What executives typically expect from a Personal Assistant",
        items: [
          "Calendar and meeting management",
          "Email and correspondence handling",
          "Travel booking",
          "Scheduling personal appointments",
          "General administrative support",
        ],
      },
      whenPARight: {
        title: "When a Personal Assistant is the right solution",
        body: "If you need someone physically present with you for most of the working day, managing real-time scheduling, handling in-person tasks and acting as an extension of you in the room, a dedicated in-house Personal Assistant is often the right choice. This is a genuine strength of the traditional model that an external service can't fully replicate.",
      },
      wherePAFalls: {
        title: "Where the traditional model starts to fall short",
        body: "Most PAs are hired to manage a calendar, not to own an operational area end-to-end. As personal life, household matters, vendor relationships, administrative bureaucracy and business operations accumulate, a single person, however good, often ends up doing the same three things repeatedly: reminding, chasing and re-explaining. The complexity doesn't reduce, it just moves onto their desk instead of yours.",
        items: [
          "Personal, household and business needs are fragmented across different people or none at all",
          "Institutional knowledge and preferences live only in one person's head, with no continuity if they're out or leave",
          "Recurring obligations depend on someone remembering to track them",
          "A single assistant has a ceiling: one set of working hours, one inbox, one set of vendor relationships",
        ],
      },
      ankoraModel: {
        title: "The Ankora model",
        body: "Ankora combines a dedicated human Operations Manager with AI orchestration to take end-to-end accountability for the areas that typically overwhelm a single assistant, personal, household, vendor, administrative, travel and selected business operations, backed by persistent memory and proactive monitoring rather than a single person's recall.",
        points: [
          { title: "Dedicated Operations Manager", body: "One person accountable for outcomes across your operational footprint, not just your calendar." },
          { title: "AI orchestration", body: "Persistent memory, tracking and monitoring that don't depend on one person's availability or memory." },
          { title: "End-to-end accountability", body: "Issues are resolved as part of the job, not escalated back to you as a new task." },
        ],
      },
      whenFullTimePA: {
        title: "When should you hire a full-time Personal Assistant instead?",
        body: "Be honest with yourself about what you actually need.",
        items: [
          "You need someone in the room with you for most of the day",
          "Your work involves frequent, real-time in-person scheduling changes",
          "You want a direct employee under your daily management, not a managed service",
          "The role is primarily calendar and correspondence, without significant personal or household complexity",
        ],
      },
      faq: [
        { q: "Is Ankora a replacement for a Personal Assistant?", a: "Not necessarily a replacement, an alternative for a different problem. If what you need is someone managing your calendar and sitting near you all day, a traditional PA remains the right choice. If the real issue is fragmented operational complexity across your personal, household and business life, Ankora is built for that instead." },
        { q: "Can Ankora manage my calendar like a Personal Assistant would?", a: "Coordinating a calendar is part of what your Operations Manager can handle, alongside the broader operational ownership Ankora provides. It's included as part of a wider scope, not offered as a standalone calendar-management service." },
        { q: "What if I already have a Personal Assistant?", a: "Many clients keep an existing Personal Assistant for day-to-day, in-person support and use Ankora for the operational areas that fall outside that role, household, vendors, administration, travel and business operations. The two models work well together rather than competing." },
        { q: "How fast does Ankora respond compared to an in-house PA?", a: "Requests are typically acknowledged the same day. Ankora doesn't offer instant, in-person, real-time responsiveness the way a PA sitting next to you would, that's a genuine strength of the in-house model." },
        { q: "Is this only for CEOs?", a: "No. Senior executives, founders and entrepreneurs at various stages use Ankora, along with busy professionals and families managing significant operational complexity." },
        { q: "Does Ankora handle personal matters as well as business ones?", a: "Yes. Personal and business operational support are both part of the model, often for the same client at the same time." },
        { q: "How is this priced compared to hiring a Personal Assistant?", a: "A full-time in-house PA is a salaried position with fixed capacity. Ankora is scoped to your actual operational footprint. Details are on our pricing page." },
        { q: "How do I know which model is right for me?", a: "A short strategy call is usually enough to tell. We'll ask about how your time is actually being spent, and tell you honestly if a traditional PA would serve you better." },
      ],
      ctaTitle: "Not sure if you need a Personal Assistant or something broader?",
      ctaBody: "Talk it through on a short strategy call.",
      cta: "Book a Strategy Call",
    },
    ankoraVsPersonalAssistant: {
      eyebrow: "Ankora vs. Personal Assistant",
      title: "Ankora vs. Personal Assistant: Which One Do You Actually Need?",
      sub: "A genuine comparison, not a sales pitch. Both models are legitimate. They fit different situations.",
      directAnswer: "A Personal Assistant is best when you need someone physically present with you, managing real-time scheduling and in-person tasks. Ankora is best when the real problem is fragmented operational ownership across personal, household, vendor, administrative, travel and business areas that need continuous, proactive management rather than task-by-task execution.",
      columnA: "Personal Assistant",
      columnB: "Ankora",
      table: [
        { dimension: "Employment model", a: "Direct employee, usually full-time", b: "Managed service with a dedicated Operations Manager" },
        { dimension: "Dedicated person", a: "Yes, one person", b: "Yes, one Operations Manager, backed by a team" },
        { dimension: "Task execution", a: "Executes assigned tasks", b: "Executes and owns outcomes end-to-end" },
        { dimension: "End-to-end ownership", a: "Depends on the individual", b: "Built into the model" },
        { dimension: "Household coordination", a: "Sometimes, informally", b: "Core part of the service" },
        { dimension: "Vendor management", a: "Ad hoc", b: "Structured, with a vetted network" },
        { dimension: "Administrative management", a: "Varies by person", b: "Core part of the service" },
        { dimension: "Business operations support", a: "Rarely the focus", b: "Available for founders and small teams" },
        { dimension: "Proactive monitoring", a: "Depends on memory and diligence", b: "Supported by AI orchestration" },
        { dimension: "Persistent memory", a: "Held by one person", b: "Persistent, AI-supported, survives staff changes" },
        { dimension: "AI orchestration", a: "Not typically used", b: "Core part of the model" },
        { dimension: "Coverage / continuity", a: "Limited to one person's hours and availability", b: "Backed by a team, not a single point of failure" },
        { dimension: "Physical-world, in-person execution", a: "Strong, present with you", b: "Coordinated remotely, not physically present" },
        { dimension: "Management burden on the client", a: "You manage and direct the person", b: "You manage the outcome, not the process" },
        { dimension: "Cost structure", a: "Fixed salary regardless of workload", b: "Scoped to your actual operational footprint" },
        { dimension: "Best-fit customer", a: "Needs someone physically present daily", b: "Needs broad operational ownership, not physical presence" },
      ],
      choosePA: {
        title: "Choose a Personal Assistant when...",
        items: [
          "You need someone in the room with you for most of the working day",
          "Your schedule changes constantly and needs real-time, in-person handling",
          "You want direct, daily management of one employee",
          "Your needs are mostly calendar and correspondence, without much personal or household complexity",
        ],
      },
      chooseAnkora: {
        title: "Choose Ankora when...",
        items: [
          "Personal, household, vendor, administrative, travel and business tasks are fragmented across too many places",
          "You want outcomes owned end-to-end, not tasks executed one at a time",
          "You don't want to manage the person doing the work, only the result",
          "You need continuity that doesn't depend on one individual's memory or availability",
        ],
      },
      whereAnkoraFits: {
        title: "Where Ankora fits",
        body: "Ankora isn't positioned as a better Personal Assistant. It's a different model built for a different problem, the operational complexity that accumulates around a busy life or growing business, owned end-to-end by a dedicated Operations Manager and AI orchestration, rather than executed task by task.",
      },
      faq: [
        { q: "Can I use both a Personal Assistant and Ankora?", a: "Yes, and many clients do. A Personal Assistant handles in-person, real-time support, while Ankora owns the broader operational areas, household, vendors, administration, travel and business, in the background." },
        { q: "Which one is more expensive?", a: "A full-time Personal Assistant is a fixed salary regardless of workload. Ankora is scoped to your actual operational footprint, so cost depends on what you need managed. Neither is inherently cheaper; they answer different needs." },
        { q: "Does Ankora offer in-person support?", a: "Ankora coordinates and manages work, including work that happens in person through vendors and providers, but your Operations Manager isn't physically present with you the way an in-house PA is." },
        { q: "What happens if my Ankora Operations Manager is unavailable?", a: "Because the model is backed by a team and AI orchestration rather than a single point of failure, coverage and continuity don't depend on one person's availability the way they would with a sole PA." },
        { q: "Is a Personal Assistant a worse choice than Ankora?", a: "No. It's a different tool for a different job. A Personal Assistant is often the better choice when you need constant physical presence and real-time, in-person responsiveness." },
        { q: "Can Ankora manage tasks a Personal Assistant currently handles?", a: "In many cases, yes, particularly administrative, vendor and household coordination. Real-time, in-person tasks generally remain better suited to an in-house PA." },
        { q: "How do I decide between the two?", a: "Ask whether the core problem is needing someone physically present with you, or needing operational complexity owned end-to-end. The first points to a Personal Assistant, the second points to Ankora." },
        { q: "How do I get started with Ankora?", a: "Book a short strategy call. We'll map your operational footprint and tell you honestly which model fits, even if that means recommending a traditional Personal Assistant instead." },
      ],
      ctaTitle: "Still deciding between a Personal Assistant and Ankora?",
      ctaBody: "A short call is the fastest way to find out which one actually fits.",
      cta: "Book a Strategy Call",
    },
  },
  footer: {
    tagline: "Operational Intelligence that gives you back time.",
    rights: "All rights reserved",
    privacy: "Privacy",
    terms: "Terms",
  },
};

export default en;
